/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Address primitive - universal reference (@(id))
 */
export interface Address {
  /**
   * Unique identifier
   */
  id: string;
  /**
   * Optional namespace qualifier
   */
  namespace?: string | null;
  /**
   * Address scope determines resolution
   */
  scope:
    | 'node'
    | {
        edge: EdgeRef;
      }
    | {
        computed: string;
      };
  /**
   * Optional version identifier
   */
  version?: string | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type AddressScope =
  | 'node'
  | {
      edge: EdgeRef;
    }
  | {
      computed: string;
    };


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Edge reference for scoped addresses
 */
export interface EdgeRef {
  source: string;
  target: string;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type PropertyValue =
  | {
      'string-val': string;
    }
  | {
      'number-val': number;
    }
  | {
      'bool-val': boolean;
    }
  | {
      'null-val': null;
    }
  | {
      'address-ref': Address;
    };


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface NodeMetadata {
  'created-at': string;
  'updated-at': string;
  version: number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface Node {
  id: string;
  'node-type'?: string | null;
  properties: [string, PropertyValue][];
  data?: string | null;
  metadata: NodeMetadata;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface Edge {
  id: string;
  source: Address;
  target: Address;
  'edge-type'?: string | null;
  weight: number;
  properties: [string, PropertyValue][];
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type Direction = 'outgoing' | 'incoming' | 'bidirectional';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface TraversalOptions {
  'max-depth'?: number | null;
  'edge-types'?: string[] | null;
  direction: Direction;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface Path {
  nodes: Node[];
  edges: Edge[];
  'total-weight': number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type EntityKind = 'agent' | 'task' | 'session' | 'human' | 'model' | 'provider' | 'program';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type EntityLifecycle = 'draft' | 'published' | 'deprecated';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface EntityMetadata {
  kind: EntityKind;
  lifecycle?: EntityLifecycle | null;
  version: number;
  created: number;
  modified: number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type AgentState = 'idle' | 'thinking' | 'executing' | 'waiting' | 'completed' | 'error';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface AgentHarness {
  'max-turns': number;
  'reflect-on-failure': boolean;
  'checkpoint-every': number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface AgentConfig {
  name: string;
  'system-prompt': string;
  tools: Address[];
  'default-model': Address;
  harness: AgentHarness;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface StepResult {
  done: boolean;
  turn?: number | null;
  reason?: string | null;
  response?: string | null;
  error?: string | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type TaskLifecycle = 'pending' | 'assigned' | 'in-progress' | 'completed' | 'failed';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type TaskPriority = 'p0' | 'p1' | 'p2' | 'p3' | 'p4';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface SuccessCriterion {
  'criterion-type': string;
  /**
   * JSON-encoded parameters
   */
  params: string;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface TaskSpec {
  inputs: string[];
  outputs: string[];
  constraints: string[];
  'success-criteria': SuccessCriterion[];
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface TaskConfig {
  title: string;
  description?: string | null;
  spec?: TaskSpec | null;
  assignee?: Address | null;
  priority?: TaskPriority | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type SessionLifecycle = 'created' | 'active' | 'paused' | 'completed';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type MessageRole = 'user' | 'assistant';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface MessageUsage {
  'input-tokens': number;
  'output-tokens': number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface SessionMessage {
  uuid: string;
  'parent-uuid'?: string | null;
  timestamp: string;
  role: MessageRole;
  content: string;
  model?: string | null;
  usage?: MessageUsage | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface SessionConfig {
  owner?: Address | null;
  'default-model': Address;
  'log-file': string;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type HumanState = 'available' | 'busy' | 'away' | 'offline';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type NotificationChannel = 'terminal' | 'email' | 'slack';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type HumanPermission = 'approve' | 'assign' | 'configure' | 'admin';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface HumanPreferences {
  'notification-channel'?: NotificationChannel | null;
  timezone?: string | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface HumanConfig {
  name: string;
  email?: string | null;
  preferences?: HumanPreferences | null;
  permissions: HumanPermission[];
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Model type discriminant
 */
export type ModelType = 'inference' | 'embedding';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Model lifecycle states
 */
export type ModelLifecycle = 'draft' | 'published' | 'deprecated';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Model parameter overrides for specific situations (inference routing)
 */
export interface SituationParams {
  /**
   * Sampling temperature override
   */
  temperature?: number;
  /**
   * Maximum tokens override
   */
  'max-tokens'?: number;
  /**
   * Top-p sampling override
   */
  'top-p'?: number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * AI model configuration for inference or embeddings
 */
export interface ModelConfig {
  /**
   * Human-readable model name
   */
  name: string;
  /**
   * Type of model (inference or embedding)
   */
  'model-type': 'inference' | 'embedding';
  /**
   * Provider-specific model identifier (e.g., 'claude-sonnet-4-5-20250929', '@cf/baai/bge-base-en-v1.5')
   */
  'backend-model': string;
  provider: Address;
  /**
   * Model lifecycle state
   */
  lifecycle: 'draft' | 'published' | 'deprecated';
  /**
   * Default temperature (inference models only)
   */
  temperature?: number | null;
  /**
   * Default max tokens (inference models only)
   */
  'max-tokens'?: number | null;
  /**
   * Default top-p (inference models only)
   */
  'top-p'?: number | null;
  /**
   * Embedding dimensions (embedding models only)
   */
  dimensions?: number | null;
  /**
   * Situational parameter overrides keyed by situation name
   */
  situations?: {
    [k: string]: SituationParams | undefined;
  } | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Provider type (currently only Cloudflare AI Gateway supported)
 */
export type ProviderType = 'cloudflare-ai-gateway';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * AI provider routing configuration
 */
export interface ProviderConfig {
  /**
   * Type of provider
   */
  'provider-type': 'cloudflare-ai-gateway';
  /**
   * Cloudflare account ID
   */
  'account-id': string;
  /**
   * Cloudflare AI Gateway ID
   */
  'gateway-id': string;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type ApprovalStatus = 'pending' | 'approved' | 'rejected';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface ApprovalRequest {
  id: string;
  description: string;
  'requested-by'?: Address | null;
  'requested-at': number;
  status: ApprovalStatus;
  'resolved-at'?: number | null;
  reason?: string | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface Notification {
  id: string;
  message: string;
  'sent-at': number;
  channel: NotificationChannel;
  read: boolean;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type CriterionResult = 'pass' | 'fail' | 'inconclusive';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type CriterionType = 'file-exists' | 'word-count' | 'pattern-match' | 'custom';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface EvaluationResult {
  'criterion-result': CriterionResult;
  reason?: string | null;
  /**
   * JSON-encoded details
   */
  details?: string | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type AggregationOp = 'count' | 'collect' | 'group' | 'sum' | 'avg';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface QueryStats {
  'duration-ms': number;
  'steps-executed': number;
  'messages-sent': number;
  'cache-hits': number;
  'cache-misses': number;
  'results-returned': number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface QueryResult {
  bindings: [string, Address[]][];
  stats: QueryStats;
  success: boolean;
  error?: string | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface EmbeddingModel {
  name: string;
  dimensions: number;
  provider: string;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface SimilarityResult {
  node: Address;
  similarity: number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface SimilarityOptions {
  'node-type'?: string | null;
  limit: number;
  'min-similarity': number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type ConvergenceStrength = 'weak' | 'moderate' | 'strong';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface ConvergenceDetection {
  nodes: Address[];
  strength: ConvergenceStrength;
  similarity: number;
  theme?: string | null;
  'detected-at': number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface SessionContext {
  session: Address;
  iteration: number;
  task?: Address | null;
  context?: [string, string][];
  'captured-at': number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface KnowledgeArtifact {
  id: string;
  'artifact-type': string;
  /**
   * JSON-encoded content
   */
  content: string;
  source: Address;
  'created-at': number;
  relevance: number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type ActorState = 'initializing' | 'ready' | 'active' | 'paused' | 'stopping' | 'stopped' | 'error';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type MessagePattern = 'tell' | 'ask' | 'stream-msg';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type SupervisionStrategy = 'restart' | 'stop' | 'resume' | 'escalate';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type NodeType = 'producer' | 'consumer' | 'relay' | 'processor' | 'hybrid';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type ProgramRuntime = 'javascript' | 'python' | 'wasm' | 'native' | 'container' | 'custom';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type ExecutionMode = 'inline' | 'worker' | 'subprocess' | 'container';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export type ProgramState = 'draft' | 'published' | 'deprecated';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface ProgramMetadata {
  name: string;
  description?: string | null;
  runtime: ProgramRuntime;
  'execution-mode': ExecutionMode;
  state: ProgramState;
  version: number;
  'input-schema'?: string | null;
  'output-schema'?: string | null;
  created: string;
  modified: string;
  tags: string[];
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

export interface InvocationResult {
  'request-id': string;
  success: boolean;
  /**
   * Binary payload as byte array
   */
  output?: number[] | null;
  error?: string | null;
  'duration-ms': number;
  timestamp: string;
  metadata: [string, string][];
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Canonical address format: @(path). Runtime-agnostic actor reference.
 */
export type CanonicalAddress = string;


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Cross-runtime wire format for messages crossing runtime boundaries
 */
export interface SharedMessage {
  /**
   * Globally unique message ID
   */
  id: string;
  /**
   * Sender canonical address
   */
  from: string;
  /**
   * Recipient canonical address
   */
  to: string;
  /**
   * Message type discriminator
   */
  type: string;
  /**
   * JSON-serializable payload
   */
  payload?: {
    [k: string]: any | undefined;
  };
  /**
   * Message pattern
   */
  pattern: 'tell' | 'ask';
  /**
   * For ask/reply correlation
   */
  correlationId?: string | null;
  /**
   * Epoch milliseconds
   */
  timestamp: number;
  /**
   * Extensible context (trace IDs, routing hints, etc.)
   */
  metadata?: {
    [k: string]: any | undefined;
  };
  /**
   * Time-to-live in milliseconds
   */
  ttl?: number | null;
  /**
   * Base64-encoded HMAC signature
   */
  signature?: string | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Transport connection states
 */
export type ConnectionState = 'disconnected' | 'connecting' | 'connected' | 'disconnecting';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Connection health status
 */
export type HealthStatus = 'unknown' | 'healthy' | 'degraded' | 'unhealthy';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Serialization content type
 */
export type ContentType = 'json' | 'msgpack' | 'protobuf' | 'cbor';


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Transport capability advertisement
 */
export interface TransportCapabilities {
  'supports-ask': boolean;
  'supports-streaming': boolean;
  'max-message-size'?: number | null;
  protocols: string[];
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Persistence snapshot metadata
 */
export interface SnapshotMetadata {
  id: string;
  version: number;
  timestamp: string;
  'size-bytes': number;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Write-ahead log entry
 */
export interface WalEntry {
  sequence: number;
  timestamp: string;
  operation: string;
  /**
   * Base64-encoded binary data
   */
  data: string;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * Transport configuration
 */
export interface TransportConfig {
  protocol: string;
  'remote-address'?: string | null;
  reconnect: boolean;
  'max-retries'?: number | null;
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * SQL query result row
 */
export interface SqlRow {
  columns: string[];
  values: (string | null)[];
}


/**
 * TypeScript type definitions for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains TypeScript type definitions for all domain model entities
 * defined in the convergence:domain@0.1.0 WIT package.
 */

/**
 * SQL query result
 */
export interface SqlResult {
  rows: SqlRow[];
  'rows-affected': number;
  'last-insert-rowid'?: number | null;
}
