/**
 * Zod validation schemas for Convergence Domain Model
 *
 * Generated from: https://convergence.dev/schemas/domain/v0.1.0
 * Schema version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-domain-types.ts
 *
 * This file contains Zod validation schemas for runtime validation
 * of domain model entities.
 */

import { z } from 'zod';

// edge-ref
export const edgeRefSchema = z.object({
  source: z.string(),
  target: z.string()
}).strict();

// node-metadata
export const nodeMetadataSchema = z.object({
  'created-at': z.string().datetime(),
  'updated-at': z.string().datetime(),
  version: z.number().int().min(0)
}).strict();

// direction
export const directionSchema = z.enum(['outgoing', 'incoming', 'bidirectional']);

// entity-kind
export const entityKindSchema = z.enum(['agent', 'task', 'session', 'human', 'model', 'provider', 'program']);

// entity-lifecycle
export const entityLifecycleSchema = z.enum(['draft', 'published', 'deprecated']);

// agent-state
export const agentStateSchema = z.enum(['idle', 'thinking', 'executing', 'waiting', 'completed', 'error']);

// agent-harness
export const agentHarnessSchema = z.object({
  'max-turns': z.number().int().min(1),
  'reflect-on-failure': z.boolean(),
  'checkpoint-every': z.number().int().min(1)
}).strict();

// step-result
export const stepResultSchema = z.object({
  done: z.boolean(),
  turn: z.number().int().min(0).nullable().optional(),
  reason: z.string().nullable().optional(),
  response: z.string().nullable().optional(),
  error: z.string().nullable().optional()
}).strict();

// task-lifecycle
export const taskLifecycleSchema = z.enum(['pending', 'assigned', 'in-progress', 'completed', 'failed']);

// task-priority
export const taskPrioritySchema = z.enum(['p0', 'p1', 'p2', 'p3', 'p4']);

// success-criterion
export const successCriterionSchema = z.object({
  'criterion-type': z.string(),
  params: z.string()
}).strict();

// session-lifecycle
export const sessionLifecycleSchema = z.enum(['created', 'active', 'paused', 'completed']);

// message-role
export const messageRoleSchema = z.enum(['user', 'assistant']);

// message-usage
export const messageUsageSchema = z.object({
  'input-tokens': z.number().int().min(0),
  'output-tokens': z.number().int().min(0)
}).strict();

// human-state
export const humanStateSchema = z.enum(['available', 'busy', 'away', 'offline']);

// notification-channel
export const notificationChannelSchema = z.enum(['terminal', 'email', 'slack']);

// human-permission
export const humanPermissionSchema = z.enum(['approve', 'assign', 'configure', 'admin']);

// model-type
export const modelTypeSchema = z.enum(['inference', 'embedding']);

// model-lifecycle
export const modelLifecycleSchema = z.enum(['draft', 'published', 'deprecated']);

// situation-params
export const situationParamsSchema = z.object({
  temperature: z.number().min(0).max(2).optional(),
  'max-tokens': z.number().int().min(1).optional(),
  'top-p': z.number().min(0).max(1).optional()
}).strict();

// provider-type
export const providerTypeSchema = z.enum(['cloudflare-ai-gateway']);

// approval-status
export const approvalStatusSchema = z.enum(['pending', 'approved', 'rejected']);

// criterion-result
export const criterionResultSchema = z.enum(['pass', 'fail', 'inconclusive']);

// criterion-type
export const criterionTypeSchema = z.enum(['file-exists', 'word-count', 'pattern-match', 'custom']);

// aggregation-op
export const aggregationOpSchema = z.enum(['count', 'collect', 'group', 'sum', 'avg']);

// query-stats
export const queryStatsSchema = z.object({
  'duration-ms': z.number().int().min(0),
  'steps-executed': z.number().int().min(0),
  'messages-sent': z.number().int().min(0),
  'cache-hits': z.number().int().min(0),
  'cache-misses': z.number().int().min(0),
  'results-returned': z.number().int().min(0)
}).strict();

// embedding-model
export const embeddingModelSchema = z.object({
  name: z.string(),
  dimensions: z.number().int().min(1),
  provider: z.string()
}).strict();

// similarity-options
export const similarityOptionsSchema = z.object({
  'node-type': z.string().nullable().optional(),
  limit: z.number().int().min(1),
  'min-similarity': z.number().min(0).max(1)
}).strict();

// convergence-strength
export const convergenceStrengthSchema = z.enum(['weak', 'moderate', 'strong']);

// actor-state
export const actorStateSchema = z.enum(['initializing', 'ready', 'active', 'paused', 'stopping', 'stopped', 'error']);

// message-pattern
export const messagePatternSchema = z.enum(['tell', 'ask', 'stream-msg']);

// supervision-strategy
export const supervisionStrategySchema = z.enum(['restart', 'stop', 'resume', 'escalate']);

// node-type
export const nodeTypeSchema = z.enum(['producer', 'consumer', 'relay', 'processor', 'hybrid']);

// program-runtime
export const programRuntimeSchema = z.enum(['javascript', 'python', 'wasm', 'native', 'container', 'custom']);

// execution-mode
export const executionModeSchema = z.enum(['inline', 'worker', 'subprocess', 'container']);

// program-state
export const programStateSchema = z.enum(['draft', 'published', 'deprecated']);

// invocation-result
export const invocationResultSchema = z.object({
  'request-id': z.string(),
  success: z.boolean(),
  output: z.array(z.number().int().min(0).max(255)).nullable().optional(),
  error: z.string().nullable().optional(),
  'duration-ms': z.number().int().min(0),
  timestamp: z.string().datetime(),
  metadata: z.array(z.tuple([z.string(), z.string()]))
}).strict();

// canonical-address
export const canonicalAddressSchema = z.string();

// connection-state
export const connectionStateSchema = z.enum(['disconnected', 'connecting', 'connected', 'disconnecting']);

// health-status
export const healthStatusSchema = z.enum(['unknown', 'healthy', 'degraded', 'unhealthy']);

// content-type
export const contentTypeSchema = z.enum(['json', 'msgpack', 'protobuf', 'cbor']);

// transport-capabilities
export const transportCapabilitiesSchema = z.object({
  'supports-ask': z.boolean(),
  'supports-streaming': z.boolean(),
  'max-message-size': z.number().int().min(1).nullable().optional(),
  protocols: z.array(z.string())
}).strict();

// snapshot-metadata
export const snapshotMetadataSchema = z.object({
  id: z.string(),
  version: z.number().int().min(0),
  timestamp: z.string().datetime(),
  'size-bytes': z.number().int().min(0)
}).strict();

// wal-entry
export const walEntrySchema = z.object({
  sequence: z.number().int().min(0),
  timestamp: z.string().datetime(),
  operation: z.string(),
  data: z.string()
}).strict();

// transport-config
export const transportConfigSchema = z.object({
  protocol: z.string(),
  'remote-address': z.string().nullable().optional(),
  reconnect: z.boolean(),
  'max-retries': z.number().int().min(0).nullable().optional()
}).strict();

// sql-row
export const sqlRowSchema = z.object({
  columns: z.array(z.string()),
  values: z.array(z.string().nullable())
}).strict();

// address-scope
export const addressScopeSchema = z.union([z.literal('node'), z.object({
  edge: edgeRefSchema
}).strict(), z.object({
  computed: z.string()
}).strict()]);

// traversal-options
export const traversalOptionsSchema = z.object({
  'max-depth': z.number().int().min(0).nullable().optional(),
  'edge-types': z.array(z.string()).nullable().optional(),
  direction: directionSchema
}).strict();

// entity-metadata
export const entityMetadataSchema = z.object({
  kind: entityKindSchema,
  lifecycle: z.union([entityLifecycleSchema, z.null()]).optional(),
  version: z.number().int().min(0),
  created: z.number().int().min(0),
  modified: z.number().int().min(0)
}).strict();

// task-spec
export const taskSpecSchema = z.object({
  inputs: z.array(z.string()),
  outputs: z.array(z.string()),
  constraints: z.array(z.string()),
  'success-criteria': z.array(successCriterionSchema)
}).strict();

// session-message
export const sessionMessageSchema = z.object({
  uuid: z.string().uuid(),
  'parent-uuid': z.string().uuid().nullable().optional(),
  timestamp: z.string().datetime(),
  role: messageRoleSchema,
  content: z.string(),
  model: z.string().nullable().optional(),
  usage: z.union([messageUsageSchema, z.null()]).optional()
}).strict();

// human-preferences
export const humanPreferencesSchema = z.object({
  'notification-channel': z.union([notificationChannelSchema, z.null()]).optional(),
  timezone: z.string().nullable().optional()
}).strict();

// notification
export const notificationSchema = z.object({
  id: z.string(),
  message: z.string(),
  'sent-at': z.number().int().min(0),
  channel: notificationChannelSchema,
  read: z.boolean()
}).strict();

// provider-config
export const providerConfigSchema = z.object({
  'provider-type': providerTypeSchema,
  'account-id': z.string(),
  'gateway-id': z.string()
}).strict();

// evaluation-result
export const evaluationResultSchema = z.object({
  'criterion-result': criterionResultSchema,
  reason: z.string().nullable().optional(),
  details: z.string().nullable().optional()
}).strict();

// program-metadata
export const programMetadataSchema = z.object({
  name: z.string(),
  description: z.string().nullable().optional(),
  runtime: programRuntimeSchema,
  'execution-mode': executionModeSchema,
  state: programStateSchema,
  version: z.number().int().min(0),
  'input-schema': z.string().nullable().optional(),
  'output-schema': z.string().nullable().optional(),
  created: z.string().datetime(),
  modified: z.string().datetime(),
  tags: z.array(z.string())
}).strict();

// sql-result
export const sqlResultSchema = z.object({
  rows: z.array(sqlRowSchema),
  'rows-affected': z.number().int().min(0),
  'last-insert-rowid': z.number().int().nullable().optional()
}).strict();

// address
export const addressSchema = z.object({
  id: z.string(),
  namespace: z.string().nullable().optional(),
  scope: addressScopeSchema,
  version: z.string().nullable().optional()
}).strict();

// human-config
export const humanConfigSchema = z.object({
  name: z.string(),
  email: z.string().email().nullable().optional(),
  preferences: z.union([humanPreferencesSchema, z.null()]).optional(),
  permissions: z.array(humanPermissionSchema)
}).strict();

// property-value
export const propertyValueSchema = z.union([z.object({
  'string-val': z.string()
}).strict(), z.object({
  'number-val': z.number()
}).strict(), z.object({
  'bool-val': z.boolean()
}).strict(), z.object({
  'null-val': z.null()
}).strict(), z.object({
  'address-ref': addressSchema
}).strict()]);

// task-config
export const taskConfigSchema = z.object({
  title: z.string(),
  description: z.string().nullable().optional(),
  spec: z.union([taskSpecSchema, z.null()]).optional(),
  assignee: z.union([addressSchema, z.null()]).optional(),
  priority: z.union([taskPrioritySchema, z.null()]).optional()
}).strict();

// model-config
export const modelConfigSchema = z.object({
  name: z.string(),
  'model-type': modelTypeSchema,
  'backend-model': z.string(),
  provider: addressSchema,
  lifecycle: modelLifecycleSchema,
  temperature: z.number().min(0).max(2).nullable().optional(),
  'max-tokens': z.number().int().min(1).nullable().optional(),
  'top-p': z.number().min(0).max(1).nullable().optional(),
  dimensions: z.number().int().min(1).nullable().optional(),
  situations: z.object({}).nullable().optional()
}).strict();

// approval-request
export const approvalRequestSchema = z.object({
  id: z.string(),
  description: z.string(),
  'requested-by': z.union([addressSchema, z.null()]).optional(),
  'requested-at': z.number().int().min(0),
  status: approvalStatusSchema,
  'resolved-at': z.number().int().min(0).nullable().optional(),
  reason: z.string().nullable().optional()
}).strict();

// query-result
export const queryResultSchema = z.object({
  bindings: z.array(z.tuple([z.string(), z.array(addressSchema)])),
  stats: queryStatsSchema,
  success: z.boolean(),
  error: z.string().nullable().optional()
}).strict();

// similarity-result
export const similarityResultSchema = z.object({
  node: addressSchema,
  similarity: z.number().min(0).max(1)
}).strict();

// convergence-detection
export const convergenceDetectionSchema = z.object({
  nodes: z.array(addressSchema),
  strength: convergenceStrengthSchema,
  similarity: z.number().min(0).max(1),
  theme: z.string().nullable().optional(),
  'detected-at': z.number().int().min(0)
}).strict();

// knowledge-artifact
export const knowledgeArtifactSchema = z.object({
  id: z.string(),
  'artifact-type': z.string(),
  content: z.string(),
  source: addressSchema,
  'created-at': z.number().int().min(0),
  relevance: z.number().min(0).max(1)
}).strict();

// node
export const nodeSchema = z.object({
  id: z.string(),
  'node-type': z.string().nullable().optional(),
  properties: z.array(z.tuple([z.string(), propertyValueSchema])),
  data: z.string().nullable().optional(),
  metadata: nodeMetadataSchema
}).strict();

// edge
export const edgeSchema = z.object({
  id: z.string(),
  source: addressSchema,
  target: addressSchema,
  'edge-type': z.string().nullable().optional(),
  weight: z.number(),
  properties: z.array(z.tuple([z.string(), propertyValueSchema]))
}).strict();

// path
export const pathSchema = z.object({
  nodes: z.array(nodeSchema),
  edges: z.array(edgeSchema),
  'total-weight': z.number()
}).strict();

// agent-config
export const agentConfigSchema = z.object({
  name: z.string(),
  'system-prompt': z.string(),
  tools: z.array(addressSchema),
  'default-model': addressSchema,
  harness: agentHarnessSchema
}).strict();

// session-config
export const sessionConfigSchema = z.object({
  owner: z.union([addressSchema, z.null()]).optional(),
  'default-model': addressSchema,
  'log-file': z.string()
}).strict();

// session-context
export const sessionContextSchema = z.object({
  session: addressSchema,
  iteration: z.number().int().min(0),
  task: z.union([addressSchema, z.null()]).optional(),
  context: z.array(z.tuple([z.string(), z.string()])).optional(),
  'captured-at': z.number().int().min(0)
}).strict();

// shared-message
export const sharedMessageSchema = z.object({
  id: z.string().uuid(),
  from: canonicalAddressSchema,
  to: canonicalAddressSchema,
  type: z.string(),
  payload: z.unknown().optional(),
  pattern: z.enum(['tell', 'ask']),
  correlationId: z.string().uuid().nullable().optional(),
  timestamp: z.number().int().min(0),
  metadata: z.object({}).optional(),
  ttl: z.number().int().min(1).nullable().optional(),
  signature: z.string().nullable().optional()
}).strict();

// Export all validators
export const DomainValidators = {
  edgeRef: edgeRefSchema,
  nodeMetadata: nodeMetadataSchema,
  direction: directionSchema,
  entityKind: entityKindSchema,
  entityLifecycle: entityLifecycleSchema,
  agentState: agentStateSchema,
  agentHarness: agentHarnessSchema,
  stepResult: stepResultSchema,
  taskLifecycle: taskLifecycleSchema,
  taskPriority: taskPrioritySchema,
  successCriterion: successCriterionSchema,
  sessionLifecycle: sessionLifecycleSchema,
  messageRole: messageRoleSchema,
  messageUsage: messageUsageSchema,
  humanState: humanStateSchema,
  notificationChannel: notificationChannelSchema,
  humanPermission: humanPermissionSchema,
  modelType: modelTypeSchema,
  modelLifecycle: modelLifecycleSchema,
  situationParams: situationParamsSchema,
  providerType: providerTypeSchema,
  approvalStatus: approvalStatusSchema,
  criterionResult: criterionResultSchema,
  criterionType: criterionTypeSchema,
  aggregationOp: aggregationOpSchema,
  queryStats: queryStatsSchema,
  embeddingModel: embeddingModelSchema,
  similarityOptions: similarityOptionsSchema,
  convergenceStrength: convergenceStrengthSchema,
  actorState: actorStateSchema,
  messagePattern: messagePatternSchema,
  supervisionStrategy: supervisionStrategySchema,
  nodeType: nodeTypeSchema,
  programRuntime: programRuntimeSchema,
  executionMode: executionModeSchema,
  programState: programStateSchema,
  invocationResult: invocationResultSchema,
  canonicalAddress: canonicalAddressSchema,
  connectionState: connectionStateSchema,
  healthStatus: healthStatusSchema,
  contentType: contentTypeSchema,
  transportCapabilities: transportCapabilitiesSchema,
  snapshotMetadata: snapshotMetadataSchema,
  walEntry: walEntrySchema,
  transportConfig: transportConfigSchema,
  sqlRow: sqlRowSchema,
  addressScope: addressScopeSchema,
  traversalOptions: traversalOptionsSchema,
  entityMetadata: entityMetadataSchema,
  taskSpec: taskSpecSchema,
  sessionMessage: sessionMessageSchema,
  humanPreferences: humanPreferencesSchema,
  notification: notificationSchema,
  providerConfig: providerConfigSchema,
  evaluationResult: evaluationResultSchema,
  programMetadata: programMetadataSchema,
  sqlResult: sqlResultSchema,
  address: addressSchema,
  humanConfig: humanConfigSchema,
  propertyValue: propertyValueSchema,
  taskConfig: taskConfigSchema,
  modelConfig: modelConfigSchema,
  approvalRequest: approvalRequestSchema,
  queryResult: queryResultSchema,
  similarityResult: similarityResultSchema,
  convergenceDetection: convergenceDetectionSchema,
  knowledgeArtifact: knowledgeArtifactSchema,
  node: nodeSchema,
  edge: edgeSchema,
  path: pathSchema,
  agentConfig: agentConfigSchema,
  sessionConfig: sessionConfigSchema,
  sessionContext: sessionContextSchema,
  sharedMessage: sharedMessageSchema,
};

// Helper function to validate any domain entity
export function validateDomainEntity<T>(
  schema: z.ZodSchema<T>,
  data: unknown
): { success: true; data: T } | { success: false; error: z.ZodError } {
  const result = schema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, error: result.error };
}
