/**
 * Zod validation schemas for Signal Hub Messages
 *
 * Generated from: https://convergence.dev/schemas/hub-messages/v0.1.0
 * Protocol version: v0.1.0
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-hub-types.ts
 *
 * This file contains Zod validation schemas for runtime validation
 * of Signal Hub message types (hub:*).
 */

import { z } from 'zod';

// hub-error-code
export const hubErrorCodeSchema = z.enum(['version_mismatch', 'unauthorized', 'rate_limited', 'unknown_actor', 'message_too_large', 'message_expired', 'timeout', 'internal_error']);

// canonical-address
export const canonicalAddressSchema = z.string();

// hub-connect-metadata
export const hubConnectMetadataSchema = z.object({
  protocolVersion: z.string(),
  authToken: z.string().optional(),
  capabilities: z.array(z.string()).min(1),
  clientMetadata: z.object({
  userAgent: z.string().optional(),
  platform: z.string().optional(),
  origin: z.string().optional()
}).strict().optional()
}).strict();

// hub-connected-payload
export const hubConnectedPayloadSchema = z.object({
  sessionId: z.string(),
  serverVersion: z.string(),
  maxMessageSize: z.number().int().min(1),
  heartbeatInterval: z.number().int().min(1),
  capabilities: z.object({
  maxActorsPerInstance: z.number().int().min(1),
  supportsBackpressure: z.boolean(),
  supportedContentTypes: z.array(z.string())
}).strict()
}).strict();

// hub-heartbeat-payload
export const hubHeartbeatPayloadSchema = z.object({
  timestamp: z.number().int().min(0)
}).strict();

// hub-heartbeat-ack-payload
export const hubHeartbeatAckPayloadSchema = z.object({
  timestamp: z.number().int().min(0),
  serverTime: z.number().int().min(0)
}).strict();

// hub-disconnect-payload
export const hubDisconnectPayloadSchema = z.object({
  reason: z.string().optional()
}).strict();

// hub-register-metadata
export const hubRegisterMetadataSchema = z.object({
  renewOnHeartbeat: z.boolean().optional()
}).strict();

// hub-discover-payload
export const hubDiscoverPayloadSchema = z.object({
  pattern: z.string(),
  limit: z.number().int().min(1).max(100).optional()
}).strict();

// hub-list-actors-payload
export const hubListActorsPayloadSchema = z.object({
  offset: z.number().int().min(0).optional(),
  limit: z.number().int().min(1).max(100).optional()
}).strict();

// hub-renew-payload
export const hubRenewPayloadSchema = z.object({
  renewalToken: z.string()
}).strict();

// hub-renewed-payload
export const hubRenewedPayloadSchema = z.object({
  expiresAt: z.number().int().min(0),
  renewalToken: z.string()
}).strict();

// hub-send-payload
export const hubSendPayloadSchema = z.object({
  type: z.string(),
  data: z.unknown()
}).strict();

// hub-send-metadata
export const hubSendMetadataSchema = z.object({
  via: z.literal('@(cloudflare/signal-hub)'),
  requireAck: z.boolean().optional(),
  traceId: z.string().optional(),
  priority: z.number().int().min(0).max(2).optional()
}).strict();

// hub-delivery-ack-payload
export const hubDeliveryAckPayloadSchema = z.object({
  messageId: z.string(),
  deliveredAt: z.number().int().min(0),
  status: z.enum(['delivered', 'queued'])
}).strict();

// hub-broadcast-payload
export const hubBroadcastPayloadSchema = z.object({
  type: z.string(),
  data: z.unknown(),
  excludeSelf: z.boolean().optional()
}).strict();

// hub-broadcast-metadata
export const hubBroadcastMetadataSchema = z.object({
  targetCapability: z.string().optional()
}).strict();

// hub-broadcast-ack-payload
export const hubBroadcastAckPayloadSchema = z.object({
  messageId: z.string(),
  deliveredCount: z.number().int().min(0),
  queuedCount: z.number().int().min(0).optional(),
  failedCount: z.number().int().min(0).optional()
}).strict();

// hub-subscribe-payload
export const hubSubscribePayloadSchema = z.object({
  topic: z.string(),
  durable: z.boolean().optional()
}).strict();

// hub-subscribed-payload
export const hubSubscribedPayloadSchema = z.object({
  topic: z.string(),
  subscriptionId: z.string()
}).strict();

// hub-publish-payload
export const hubPublishPayloadSchema = z.object({
  topic: z.string(),
  type: z.string(),
  data: z.unknown()
}).strict();

// hub-published-payload
export const hubPublishedPayloadSchema = z.object({
  topic: z.string(),
  subscriberCount: z.number().int().min(0)
}).strict();

// hub-unsubscribe-payload
export const hubUnsubscribePayloadSchema = z.object({
  subscriptionId: z.string()
}).strict();

// hub-pause-payload
export const hubPausePayloadSchema = z.object({
  reason: z.string()
}).strict();

// hub-resume-payload
export const hubResumePayloadSchema = z.object({});

// hub-queue-stats-payload
export const hubQueueStatsPayloadSchema = z.object({});

// hub-queue-stats-response-payload
export const hubQueueStatsResponsePayloadSchema = z.object({
  queueDepth: z.number().int().min(0),
  processingRate: z.number().min(0),
  pauseThreshold: z.number().int().min(0),
  resumeThreshold: z.number().int().min(0)
}).strict();

// hub-unauthorized-payload
export const hubUnauthorizedPayloadSchema = z.object({
  action: z.string(),
  reason: z.string()
}).strict();

// hub-rate-limited-payload
export const hubRateLimitedPayloadSchema = z.object({
  retryAfter: z.number().int().min(0)
}).strict();

// hub-version-mismatch-payload
export const hubVersionMismatchPayloadSchema = z.object({
  clientVersion: z.string(),
  serverVersion: z.string(),
  supportedVersions: z.array(z.string()),
  message: z.string()
}).strict();

// hub-message-too-large-payload
export const hubMessageTooLargePayloadSchema = z.object({
  messageSize: z.number().int().min(0),
  maxSize: z.number().int().min(0)
}).strict();

// channel-error-code
export const channelErrorCodeSchema = z.enum(['address_not_found', 'channel_id_collision', 'channel_not_open', 'actor_rejected', 'internal_error']);

// channel-close-payload
export const channelClosePayloadSchema = z.object({
  channelId: z.number().int().min(0).max(4294967295),
  reason: z.string().optional()
}).strict();

// ai-actor-address
export const aiActorAddressSchema = z.string();

// ai-inference-request-payload
export const aiInferenceRequestPayloadSchema = z.object({
  messages: z.array(z.object({
  role: z.enum(['system', 'user', 'assistant', 'tool']),
  content: z.string()
})),
  model: z.string().optional(),
  stream: z.boolean().optional(),
  temperature: z.number().min(0).max(2).optional(),
  maxTokens: z.number().int().min(1).optional()
});

// ai-inference-response-payload
export const aiInferenceResponsePayloadSchema = z.object({
  content: z.string(),
  model: z.string().optional(),
  usage: z.object({
  promptTokens: z.number().int().optional(),
  completionTokens: z.number().int().optional(),
  totalTokens: z.number().int().optional()
}).strict().optional(),
  finishReason: z.string().optional()
});

// ai-inference-chunk-payload
export const aiInferenceChunkPayloadSchema = z.object({
  delta: z.string(),
  index: z.number().int().optional()
}).strict();

// ai-tts-request-payload
export const aiTtsRequestPayloadSchema = z.object({
  text: z.string(),
  voice: z.string().optional(),
  encoding: z.enum(['opus', 'mp3', 'linear16']).optional(),
  sampleRate: z.number().int().optional()
}).strict();

// ai-stt-start-payload
export const aiSttStartPayloadSchema = z.object({
  encoding: z.enum(['opus', 'mp3', 'linear16', 'mulaw']).optional(),
  sampleRate: z.number().int().optional(),
  language: z.string().optional(),
  model: z.string().optional()
}).strict();

// ai-stt-transcript-payload
export const aiSttTranscriptPayloadSchema = z.object({
  transcript: z.string(),
  isFinal: z.boolean(),
  confidence: z.number().min(0).max(1).optional(),
  words: z.array(z.object({
  word: z.string(),
  start: z.number(),
  end: z.number(),
  confidence: z.number().optional()
})).optional()
}).strict();

// ai-session-create-payload
export const aiSessionCreatePayloadSchema = z.object({
  userId: z.string(),
  metadata: z.object({}).optional()
}).strict();

// hub-error-payload
export const hubErrorPayloadSchema = z.object({
  code: hubErrorCodeSchema,
  message: z.string(),
  details: z.unknown().optional(),
  retryable: z.boolean()
}).strict();

// actor-registration
export const actorRegistrationSchema = z.object({
  actorAddress: canonicalAddressSchema,
  capabilities: z.array(z.string()),
  metadata: z.object({}),
  connectionId: z.string(),
  registeredAt: z.number().int().min(0),
  expiresAt: z.number().int().min(0),
  version: z.number().int().min(0)
}).strict();

// hub-connected-metadata
export const hubConnectedMetadataSchema = z.object({
  actorIdentity: canonicalAddressSchema.optional()
}).strict();

// hub-register-payload
export const hubRegisterPayloadSchema = z.object({
  actorAddress: canonicalAddressSchema,
  capabilities: z.array(z.string()).min(1),
  metadata: z.object({}),
  ttlSeconds: z.number().int().min(60).max(3600).optional()
}).strict();

// hub-registered-payload
export const hubRegisteredPayloadSchema = z.object({
  actorAddress: canonicalAddressSchema,
  expiresAt: z.number().int().min(0),
  renewalToken: z.string(),
  version: z.number().int().min(0)
}).strict();

// hub-unregister-payload
export const hubUnregisterPayloadSchema = z.object({
  actorAddress: canonicalAddressSchema
}).strict();

// hub-unknown-actor-payload
export const hubUnknownActorPayloadSchema = z.object({
  actorAddress: canonicalAddressSchema,
  message: z.string()
}).strict();

// channel-open-payload
export const channelOpenPayloadSchema = z.object({
  address: canonicalAddressSchema
}).strict();

// channel-opened-payload
export const channelOpenedPayloadSchema = z.object({
  channelId: z.number().int().min(0).max(4294967295),
  address: canonicalAddressSchema
}).strict();

// channel-error-payload
export const channelErrorPayloadSchema = z.object({
  channelId: z.number().int().min(0).max(4294967295),
  code: channelErrorCodeSchema,
  message: z.string()
}).strict();

// ai-session-state-payload
export const aiSessionStatePayloadSchema = z.object({
  userId: z.string(),
  activeActors: z.array(aiActorAddressSchema),
  createdAt: z.number().int(),
  metadata: z.object({}).optional()
}).strict();

// hub-discovered-payload
export const hubDiscoveredPayloadSchema = z.object({
  actors: z.array(actorRegistrationSchema),
  hasMore: z.boolean()
}).strict();

// hub-actor-list-payload
export const hubActorListPayloadSchema = z.object({
  actors: z.array(actorRegistrationSchema),
  total: z.number().int().min(0),
  offset: z.number().int().min(0),
  limit: z.number().int().min(1),
  hasMore: z.boolean()
}).strict();

// Export all validators
export const HubMessageValidators = {
  hubErrorCode: hubErrorCodeSchema,
  canonicalAddress: canonicalAddressSchema,
  hubConnectMetadata: hubConnectMetadataSchema,
  hubConnectedPayload: hubConnectedPayloadSchema,
  hubHeartbeatPayload: hubHeartbeatPayloadSchema,
  hubHeartbeatAckPayload: hubHeartbeatAckPayloadSchema,
  hubDisconnectPayload: hubDisconnectPayloadSchema,
  hubRegisterMetadata: hubRegisterMetadataSchema,
  hubDiscoverPayload: hubDiscoverPayloadSchema,
  hubListActorsPayload: hubListActorsPayloadSchema,
  hubRenewPayload: hubRenewPayloadSchema,
  hubRenewedPayload: hubRenewedPayloadSchema,
  hubSendPayload: hubSendPayloadSchema,
  hubSendMetadata: hubSendMetadataSchema,
  hubDeliveryAckPayload: hubDeliveryAckPayloadSchema,
  hubBroadcastPayload: hubBroadcastPayloadSchema,
  hubBroadcastMetadata: hubBroadcastMetadataSchema,
  hubBroadcastAckPayload: hubBroadcastAckPayloadSchema,
  hubSubscribePayload: hubSubscribePayloadSchema,
  hubSubscribedPayload: hubSubscribedPayloadSchema,
  hubPublishPayload: hubPublishPayloadSchema,
  hubPublishedPayload: hubPublishedPayloadSchema,
  hubUnsubscribePayload: hubUnsubscribePayloadSchema,
  hubPausePayload: hubPausePayloadSchema,
  hubResumePayload: hubResumePayloadSchema,
  hubQueueStatsPayload: hubQueueStatsPayloadSchema,
  hubQueueStatsResponsePayload: hubQueueStatsResponsePayloadSchema,
  hubUnauthorizedPayload: hubUnauthorizedPayloadSchema,
  hubRateLimitedPayload: hubRateLimitedPayloadSchema,
  hubVersionMismatchPayload: hubVersionMismatchPayloadSchema,
  hubMessageTooLargePayload: hubMessageTooLargePayloadSchema,
  channelErrorCode: channelErrorCodeSchema,
  channelClosePayload: channelClosePayloadSchema,
  aiActorAddress: aiActorAddressSchema,
  aiInferenceRequestPayload: aiInferenceRequestPayloadSchema,
  aiInferenceResponsePayload: aiInferenceResponsePayloadSchema,
  aiInferenceChunkPayload: aiInferenceChunkPayloadSchema,
  aiTtsRequestPayload: aiTtsRequestPayloadSchema,
  aiSttStartPayload: aiSttStartPayloadSchema,
  aiSttTranscriptPayload: aiSttTranscriptPayloadSchema,
  aiSessionCreatePayload: aiSessionCreatePayloadSchema,
  hubErrorPayload: hubErrorPayloadSchema,
  actorRegistration: actorRegistrationSchema,
  hubConnectedMetadata: hubConnectedMetadataSchema,
  hubRegisterPayload: hubRegisterPayloadSchema,
  hubRegisteredPayload: hubRegisteredPayloadSchema,
  hubUnregisterPayload: hubUnregisterPayloadSchema,
  hubUnknownActorPayload: hubUnknownActorPayloadSchema,
  channelOpenPayload: channelOpenPayloadSchema,
  channelOpenedPayload: channelOpenedPayloadSchema,
  channelErrorPayload: channelErrorPayloadSchema,
  aiSessionStatePayload: aiSessionStatePayloadSchema,
  hubDiscoveredPayload: hubDiscoveredPayloadSchema,
  hubActorListPayload: hubActorListPayloadSchema,
};

// Helper function to validate any hub message
export function validateHubMessage<T>(
  schema: z.ZodSchema<T>,
  data: unknown
): { success: true; data: T } | { success: false; error: z.ZodError } {
  const result = schema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, error: result.error };
}
