/**
 * @agentic-primer/protocols
 *
 * Convergence domain protocol types and validators.
 *
 * Source of truth: schema/domain.schema.json (JSON Schema Draft 07)
 * Generated types: domain.types.ts (TypeScript)
 * Runtime validation: domain.validators.ts (Zod)
 * WASM interface: wit/domain.wit (WebAssembly Component Model)
 *
 * Hub Messages: schema/hub-messages.schema.json (JSON Schema Draft 07)
 * Hub validators: hub-messages.validators.ts (Zod)
 */

// Re-export all generated types EXCEPT those refined in shared-message
export {
  type Address,
  type AddressScope,
  type EdgeRef,
  type PropertyValue,
  type NodeMetadata,
  type Node,
  type Edge,
  type Direction,
  type TraversalOptions,
  type Path,
  type EntityKind,
  type EntityLifecycle,
  type EntityMetadata,
  type AgentState,
  type AgentHarness,
  type AgentConfig,
  type StepResult,
  type TaskLifecycle,
  type TaskPriority,
  type SuccessCriterion,
  type TaskSpec,
  type TaskConfig,
  type SessionLifecycle,
  type MessageRole,
  type MessageUsage,
  type SessionMessage,
  type SessionConfig,
  type HumanState,
  type NotificationChannel,
  type HumanPermission,
  type HumanPreferences,
  type HumanConfig,
  type ModelType,
  type ModelLifecycle,
  type SituationParams,
  type ModelConfig,
  type ProviderType,
  type ProviderConfig,
  type ApprovalStatus,
  type ApprovalRequest,
  type Notification,
  type CriterionResult,
  type CriterionType,
  type EvaluationResult,
  type AggregationOp,
  type QueryStats,
  type QueryResult,
  type EmbeddingModel,
  type SimilarityResult,
  type SimilarityOptions,
  type ConvergenceStrength,
  type ConvergenceDetection,
  type SessionContext,
  type KnowledgeArtifact,
  type ActorState,
  type MessagePattern,
  type SupervisionStrategy,
  type NodeType,
  type ProgramRuntime,
  type ExecutionMode,
  type ProgramState,
  type ProgramMetadata,
  type InvocationResult,
  // New infrastructure types (generated)
  type TransportCapabilities,
  type SnapshotMetadata,
  type WalEntry,
} from './domain.types.js';

// Re-export validators (excluding those refined in shared-message)
export {
  addressSchema,
  addressScopeSchema,
  edgeRefSchema,
  propertyValueSchema,
  nodeMetadataSchema,
  nodeSchema,
  edgeSchema,
  directionSchema,
  traversalOptionsSchema,
  pathSchema,
  entityKindSchema,
  entityLifecycleSchema,
  entityMetadataSchema,
  agentStateSchema,
  agentHarnessSchema,
  agentConfigSchema,
  stepResultSchema,
  taskLifecycleSchema,
  taskPrioritySchema,
  successCriterionSchema,
  taskSpecSchema,
  taskConfigSchema,
  sessionLifecycleSchema,
  messageRoleSchema,
  messageUsageSchema,
  sessionMessageSchema,
  sessionConfigSchema,
  humanStateSchema,
  notificationChannelSchema,
  humanPermissionSchema,
  humanPreferencesSchema,
  humanConfigSchema,
  modelTypeSchema,
  modelLifecycleSchema,
  situationParamsSchema,
  modelConfigSchema,
  providerTypeSchema,
  providerConfigSchema,
  approvalStatusSchema,
  approvalRequestSchema,
  notificationSchema,
  criterionResultSchema,
  criterionTypeSchema,
  evaluationResultSchema,
  aggregationOpSchema,
  queryStatsSchema,
  queryResultSchema,
  embeddingModelSchema,
  similarityResultSchema,
  similarityOptionsSchema,
  convergenceStrengthSchema,
  convergenceDetectionSchema,
  sessionContextSchema,
  knowledgeArtifactSchema,
  actorStateSchema,
  messagePatternSchema,
  supervisionStrategySchema,
  nodeTypeSchema,
  programRuntimeSchema,
  executionModeSchema,
  programStateSchema,
  programMetadataSchema,
  invocationResultSchema,
  connectionStateSchema,
  healthStatusSchema,
  contentTypeSchema,
  transportCapabilitiesSchema,
  snapshotMetadataSchema,
  walEntrySchema,
  DomainValidators,
  validateDomainEntity,
} from './domain.validators.js';

// Re-export shared message types (cross-runtime wire format, refined types + converters)
export * from './shared-message.js';

// Re-export hub message validators (Signal Hub protocol messages)
// Note: Use named import to avoid conflicts with domain validators
export { HubMessageValidators, validateHubMessage } from './hub-messages.validators.js';
