name: Implementation Task
description: Create an implementation task for development work
title: "[Implement] "
labels: ["implementation", "copilot"]
assignees:
  - brian-ln
body:
  - type: markdown
    attributes:
      value: |
        ## Implementation Task
        Use this template for development and implementation tasks.
  
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be implemented?
      placeholder: Describe the implementation task
    validations:
      required: true
  
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List specific requirements
      placeholder: |
        - Requirement 1
        - Requirement 2
    validations:
      required: false
  
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: false
  
  - type: textarea
    id: technical
    attributes:
      label: Technical Details
      description: Any technical constraints or implementation notes
      placeholder: Implementation details, constraints, dependencies
    validations:
      required: false
