#!/bin/sh
#
# Install enhanced pre-commit hook with SQL injection checks
# Epic: agentic-primer-0lg.2
#

# Get repository root
REPO_ROOT=$(git rev-parse --show-toplevel)
HOOK_FILE="$REPO_ROOT/.git/hooks/pre-commit"
SQL_CHECK_SCRIPT="$REPO_ROOT/scripts/pre-commit-sql-check.sh"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "Installing enhanced pre-commit hook with SQL injection checks..."

# Backup existing hook if it exists
if [ -f "$HOOK_FILE" ]; then
    BACKUP_FILE="$HOOK_FILE.backup.$(date +%s)"
    cp "$HOOK_FILE" "$BACKUP_FILE"
    echo "${YELLOW}Backed up existing pre-commit hook to: $BACKUP_FILE${NC}"
fi

# Read existing hook content
EXISTING_CONTENT=""
if [ -f "$HOOK_FILE" ]; then
    EXISTING_CONTENT=$(cat "$HOOK_FILE")
fi

# Create new pre-commit hook that chains with existing one
cat > "$HOOK_FILE" << 'HOOK_EOF'
#!/bin/sh
#
# Enhanced pre-commit hook with SQL injection checks
# Generated by install-pre-commit-hook.sh
#

# Get repository root
REPO_ROOT=$(git rev-parse --show-toplevel)

# Run SQL injection checks first
SQL_CHECK_SCRIPT="$REPO_ROOT/scripts/pre-commit-sql-check.sh"
if [ -x "$SQL_CHECK_SCRIPT" ]; then
    "$SQL_CHECK_SCRIPT"
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
        exit $EXIT_CODE
    fi
else
    echo "Warning: SQL check script not found or not executable" >&2
fi

HOOK_EOF

# Append existing bd hook content (the part after the shebang)
if echo "$EXISTING_CONTENT" | grep -q "bd sync --flush-only"; then
    echo "" >> "$HOOK_FILE"
    echo "# Original bd pre-commit hook functionality" >> "$HOOK_FILE"
    echo "$EXISTING_CONTENT" | sed '1,/^#!/d' >> "$HOOK_FILE"
fi

# Make hook executable
chmod +x "$HOOK_FILE"

echo "${GREEN}✅ Pre-commit hook installed successfully${NC}"
echo ""
echo "The hook will now:"
echo "  1. Check for SQL injection vulnerabilities in staged TypeScript files"
echo "  2. Run existing bd sync functionality"
echo ""
echo "To test the hook:"
echo "  git add <file>"
echo "  git commit -m \"test\""
